# Generated by Django 2.1.1 on 2020-04-29 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=64)),
                ('profile_photo', models.FileField(blank=True, null=True, upload_to='')),
                ('city', models.IntegerField(choices=[(1, 'Hanoi'), (2, 'TP HCM')], default=1)),
                ('home', models.IntegerField(choices=[(1, 'D1'), (2, 'D2'), (3, 'D3'), (4, 'D4'), (5, 'D'), (6, 'D6'), (6, 'D6'), (7, 'D7')], default=1)),
                ('introduce', models.TextField()),
                ('member', models.IntegerField(choices=[(1, '5 vs 5/ 6 vs 6'), (2, '7 vs 7/ 8 vs 8'), (3, '11 vs 11')], default=1)),
                ('made_on', models.DateField(default=django.utils.timezone.now)),
                ('book', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
