# Generated by Django 2.1.1 on 2020-04-29 10:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.IntegerField(choices=[(1, 'D1'), (2, 'D2'), (3, 'D3'), (4, 'D4'), (5, 'D'), (6, 'D6'), (6, 'D6'), (7, 'D7')], default=1)),
                ('member', models.IntegerField(choices=[(1, '5 vs 5/ 6 vs 6'), (2, '7 vs 7/ 8 vs 8'), (3, '11 vs 11')], default=1)),
                ('made_on', models.DateField(default=django.utils.timezone.now)),
                ('book', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='member',
            field=models.CharField(max_length=20),
        ),
    ]
