# Generated by Django 2.1.5 on 2020-04-29 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_auto_20200429_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='made_on',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='book',
            new_name='time',
        ),
    ]
