# Generated by Django 2.1.5 on 2020-04-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_auto_20200429_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='home',
            field=models.IntegerField(choices=[(1, 'D1'), (2, 'D2'), (3, 'D3'), (4, 'D4'), (5, 'D5'), (6, 'D6'), (6, 'D6'), (7, 'D7')], default=1),
        ),
    ]
