# Generated by Django 2.1.5 on 2020-04-29 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_auto_20200429_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='time',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='date',
            new_name='made_on',
        ),
    ]
